language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install gcc-4.9 g++-4.9
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 20
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 20
  - sudo update-alternatives --config gcc
  - sudo update-alternatives --config g++
  - BUILD_ONLY=true npm install nodegit/nodegit
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
